### ISSUE TITLE
[FEATURE] - Rename Helllike dreams to Infernal

### ISSUE THREAD

**Issue by statecouncil** [QarsoonMeel/DreamersDreams#25]
Helllike sounds a little strange. Alternatively:
- Infernal
- Diabolical
- Traumatizing
- Agonizing
- Legendary (since, you know, that's what they kind of are)

**Comment by QarsoonMeel** [comment]
Helllike is just a defname (internal name that is supposed to be only read by code). Label is the name that appears in game. I'm happy to discuss those names. Right now it is named Hellish which sounds a bit lame imo. I like infernal :P

**Comment by statecouncil** [comment]
Yeah, I could live with Infernal. What do you think about Legendary? We discussed making the extreme dreams dependant on the pawn's extremes, so throwing both ends of the spectrum into the same category (at least seemingly) seems to make sense. But I think we need to figure out the exact dream quality mechanics first.

**Comment by QarsoonMeel** [comment]
Dreams inherit statistics from qualities. That's the whole point. If you make negative legendaries and positive in one quality then you will have to overwrite that on each dream. I would dare to say that it is a good idea to rethink naming of most of the qualities so far.

**Comment by QarsoonMeel** [comment]
Just change Label of the tag. DefName needs to stay the same and as I said it is only for internal stuff. User does not see that.

**Comment by statecouncil** [comment]
As discussed: What if we remove mentions of dream qualities in general? Directly mention "Kas dreamt about potted plants!" instead of "Kas is having a Legendary dream!"

**Comment by QarsoonMeel** [comment]
We can combine both but I wanna keep the tag label in the notification alert.

**Comment by statecouncil** [comment]
Sure, works for me.

**Comment by QarsoonMeel** [comment]
That would mean we need to cut out "I dreamt about" part of the label in each dream. Let's take care of that issue after the release of 2.3.0.
