### ISSUE TITLE
[FEATURE] - More Dream Restrictions/Requirements

### ISSUE THREAD

**Issue by statecouncil** [QarsoonMeel/DreamersDreams#28]
To Do:
- [x] Specific Gender
- [x] Pawn lost a limb
- [x] Pawn had a social interaction in the last 24hrs like getting rebuffed, social fight, insulted
- [x] Had some lovin'
- [x] Has the Pawn travelled/been on a caravan?
- [x] Pawn is the only one in the colony
- [ ] #49
- [x] Check if Pawn passed out on the ground (although that might warrant not dreaming at all) **thats pointless pawn is gonna stand up before getting a dream**
- [x] Pawn took drugs/slept while high (!!!) - possibly differentiate between different drugs here **you can check for thought for now**
- [ ] #50

Not gonna do for now (unless someone changes my mind :D ):
- Having an Ideoligion , having a specific Meme, having a specific Tenet, having a specific base Ideology (Theist, Archist, etc.) _you can check for precept_
- Pawn has a specific weapon/apparel equipped (maybe better: weapon category (damage type?)/apparel category (?) **this needs to be more specific**
- Bed quality
- Specific event just happend (48hrs), maybe clumped together into categories like "Beneficial Event", "Bad Event", "Natural Event", "Enemy Action", "Personal Event", etc. - gotta do more research here, if they're too general the dreams won't be specific enough
- Colony quest fulfilled or new quest obtained, possibly sorted by faction?
- Become enemies with a faction or made peace 
- Pawn is sleeping in the same room as other pawn/furniture/animal/dirt/etc.
- Reached a new tech level/researched a key technology **we can make check for tech**
- Recreation type the Pawn did in the last 24hrs **needs to use Harmony which I would rather avoid**
- Pawn spent most of the day (>10hrs) doing a specific job or improving a specific skill **would need to make specific category for that i think, although i know how to check if pawn already reached a cap on learning for a skill**

**Comment by statecouncil** [comment]
I just realized Issue#37 (https://github.com/QarsoonMeel/DreamersDreams/issues/37) can very easily also be solved via tags. Can we have something like <requiredSpecies>? Alternatively, the argument _speciesHuman_ for <requiredBodyStates>, etc.

**Comment by QarsoonMeel** [comment]
Nope, it can't be. This code is literally not running on other races.

**Comment by statecouncil** [comment]
Oh. Alright. What can we do instead?

**Comment by QarsoonMeel** [comment]
I will sort it out. I need to patch the Def of each mod so it runs our mod. I understand you want to check for race in general?

**Comment by statecouncil** [comment]
For starters, being able to say "This dream can only/never occur to X" already gives us a wide angle of customization. Would that work?

**Comment by QarsoonMeel** [comment]
So, you want the same thing as with thoughts/body/mind etc but for race? That is possible, yes. First we would need support for those races though.
