### ISSUE TITLE
[FEATURE] - More Dreams, Rework XML

### ISSUE THREAD

**Issue by statecouncil** [QarsoonMeel/DreamersDreams#30]
There should be at least enough dreams to cover the most likely combinations of categories and tags. Goal: Another 50 "generic" dreams (1-3 sentences each) covering every pawn Status and the six most likely Categories and another 12 Legendary/Epic/Helllike/Terrorising dreams, spread over pawn Status.

EDIT: Idea: Non-dreams!
Certain low-quality dreams in the range between Exciting and Disturbing could simply be actions the pawn did while sleeping or trying to sleep. Not too many, maybe just one per category. Things like _Shifted around all night_, _Snuggled against Lover/Fiance/Husband/Wife_, _Woke up with no memory of a dream_, _Peed the bed_. Maybe some of these have a higher chance of occurring with Sleepwalkers.

- [x] Get external dream inventory running
- [x] Raise dreams to 100
- [x] Non-dream concepts
- [x] Rework XML via dream inventory and new tags
- [x] Add more dreams using dream inventory data, especially more good dreams

**Comment by QarsoonMeel** [comment]
![image](https://user-images.githubusercontent.com/60186996/134000396-f986cfce-d631-4328-9fec-b171dfa78405.png)
Is there any reason why you use requiredOneOf instead of required? Is it for the future?

**Comment by QarsoonMeel** [comment]
![image](https://user-images.githubusercontent.com/60186996/134000507-089c753a-ec3f-4901-8f0f-a158f64f056c.png)
Why both prisoner and guest? That is very specific and not sure how does it fit the dream?

**Comment by QarsoonMeel** [comment]
![image](https://user-images.githubusercontent.com/60186996/134000680-76170a22-0e01-4b06-8675-49008254dd36.png)
Colonist tag for that?

**Comment by QarsoonMeel** [comment]
![image](https://user-images.githubusercontent.com/60186996/134000772-4756c9c8-0d02-491b-bf24-7626c8bb9e6c.png)
Need author for this one.

**Comment by QarsoonMeel** [comment]
![image](https://user-images.githubusercontent.com/60186996/134001078-89459b47-3f41-4d18-90f5-bd27d5c571ff.png)
Required? Not conflicting?

**Comment by QarsoonMeel** [comment]
![image](https://user-images.githubusercontent.com/60186996/134001321-f2c4d678-6d0f-4397-8518-bf8a70babe12.png)
Tribal exclusive? :P

**Comment by statecouncil** [comment]
> ![image](https://user-images.githubusercontent.com/60186996/134000396-f986cfce-d631-4328-9fec-b171dfa78405.png)
> Is there any reason why you use requiredOneOf instead of required? Is it for the future?

Use of requiredOneOf allows us to add more tags later on, no? Seems like a good idea to use it by default.

**Comment by QarsoonMeel** [comment]
![image](https://user-images.githubusercontent.com/60186996/134001453-69ebcb6b-b720-4880-9f41-45c65eff88ed.png)
I would to conflicting - Healthy instead

**Comment by QarsoonMeel** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/60186996/134000396-f986cfce-d631-4328-9fec-b171dfa78405.png)
> > Is there any reason why you use requiredOneOf instead of required? Is it for the future?
> 
> Use of requiredOneOf allows us to add more tags later on, no? Seems like a good idea to use it by default.

Okay fair enough. It is fine by me.

**Comment by statecouncil** [comment]
> ![image](https://user-images.githubusercontent.com/60186996/134000507-089c753a-ec3f-4901-8f0f-a158f64f056c.png)
> Why both prisoner and guest? That is very specific and not sure how does it fit the dream?

Mistake, thanks for spotting. Should have been OneOf.

**Comment by statecouncil** [comment]
> ![image](https://user-images.githubusercontent.com/60186996/134000680-76170a22-0e01-4b06-8675-49008254dd36.png)
> Colonist tag for that?

Yeah, or at Outlander. Good point.

**Comment by QarsoonMeel** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/60186996/134000507-089c753a-ec3f-4901-8f0f-a158f64f056c.png)
> > Why both prisoner and guest? That is very specific and not sure how does it fit the dream?
> 
> Mistake, thanks for spotting. Should have been OneOf.

Wait why do you want to reserve it for guest and prisoners though

**Comment by statecouncil** [comment]
> There are a lot of dreams without author. Did you forget about them?

Check the Dream Inventory. There _are_ a lot of dreams without author. I'm also not adding myself as author, because my name can already be found elsewhere.

**Comment by QarsoonMeel** [comment]
![image](https://user-images.githubusercontent.com/60186996/134001856-adb66e9c-8ef8-493c-a24e-b38d748a6d81.png)
Duplicates?

**Comment by statecouncil** [comment]
> ![image](https://user-images.githubusercontent.com/60186996/134001078-89459b47-3f41-4d18-90f5-bd27d5c571ff.png)
> Required? Not conflicting?

No, that's on purpose. There's a bad cheese dream, exclusive for cannibals, and a good cheese dream, exclusive for everyone but cannibals.

**Comment by statecouncil** [comment]
> ![image](https://user-images.githubusercontent.com/60186996/134001453-69ebcb6b-b720-4880-9f41-45c65eff88ed.png)
> I would to conflicting - Healthy instead

Hmm, how does that differ, technically?

**Comment by QarsoonMeel** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/60186996/134001078-89459b47-3f41-4d18-90f5-bd27d5c571ff.png)
> > Required? Not conflicting?
> 
> No, that's on purpose. There's a bad cheese dream, exclusive for cannibals, and a good cheese dream, exclusive for everyone but cannibals.

Clever :)

**Comment by statecouncil** [comment]
> > > ![image](https://user-images.githubusercontent.com/60186996/134000507-089c753a-ec3f-4901-8f0f-a158f64f056c.png)
> > > Why both prisoner and guest? That is very specific and not sure how does it fit the dream?
> > 
> > 
> > Mistake, thanks for spotting. Should have been OneOf.
> 
> Wait why do you want to reserve it for guest and prisoners though

Eh, I'm a dummy. Obviously that should be conflicting. Slaves are okay, since they do walk around the colony.

**Comment by QarsoonMeel** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/60186996/134001453-69ebcb6b-b720-4880-9f41-45c65eff88ed.png)
> > I would to conflicting - Healthy instead
> 
> Hmm, how does that differ, technically?

So one is: give this dream to pawns who are injured

There other is: don't give this dream to pawns who are healthy

**Comment by QarsoonMeel** [comment]
> 
> 
> > > > ![image](https://user-images.githubusercontent.com/60186996/134000507-089c753a-ec3f-4901-8f0f-a158f64f056c.png)
> > > > Why both prisoner and guest? That is very specific and not sure how does it fit the dream?
> > > 
> > > 
> > > Mistake, thanks for spotting. Should have been OneOf.
> > 
> > 
> > Wait why do you want to reserve it for guest and prisoners though
> 
> Eh, I'm a dummy. Obviously that should be conflicting. Slaves are okay, since they do walk around the colony.

I mean this dream should be limited to Colonists imo

**Comment by statecouncil** [comment]
> ![image](https://user-images.githubusercontent.com/60186996/134001856-adb66e9c-8ef8-493c-a24e-b38d748a6d81.png)
> Duplicates?

Oops. Yeah, the first one should be gone.

**Comment by statecouncil** [comment]
> > > ![image](https://user-images.githubusercontent.com/60186996/134001453-69ebcb6b-b720-4880-9f41-45c65eff88ed.png)
> > > I would to conflicting - Healthy instead
> > 
> > 
> > Hmm, how does that differ, technically?
> 
> So one is: give this dream to pawns who are injured
> 
> There other is: don't give this dream to pawns who are healthy

Right. But what difference does that make, in the end? No sarcasm, I'm really not sure.

**Comment by QarsoonMeel** [comment]
![image](https://user-images.githubusercontent.com/60186996/134002606-71398e4b-f0f8-4c12-ac14-ebc06e6c851b.png)
This is a good one but the label won't fit. Label can have a minimum of like 25-30 characters :/

**Comment by statecouncil** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/60186996/134000507-089c753a-ec3f-4901-8f0f-a158f64f056c.png)
> > > > > Why both prisoner and guest? That is very specific and not sure how does it fit the dream?
> > > > 
> > > > 
> > > > Mistake, thanks for spotting. Should have been OneOf.
> > > 
> > > 
> > > Wait why do you want to reserve it for guest and prisoners though
> > 
> > 
> > Eh, I'm a dummy. Obviously that should be conflicting. Slaves are okay, since they do walk around the colony.
> 
> I mean this dream should be limited to Colonists imo

Fair enough.

**Comment by statecouncil** [comment]
> ![image](https://user-images.githubusercontent.com/60186996/134002606-71398e4b-f0f8-4c12-ac14-ebc06e6c851b.png)
> This is a good one but the label won't fit. Label can have a minimum of like 25-30 characters :/

Ah, I didn't know that. Wait, really? I could have sworn I saw longer ones.

**Comment by QarsoonMeel** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/60186996/134002606-71398e4b-f0f8-4c12-ac14-ebc06e6c851b.png)
> > This is a good one but the label won't fit. Label can have a minimum of like 25-30 characters :/
> 
> Ah, I didn't know that. Wait, really? I could have sworn I saw longer ones.

Not really unfortunately :/

**Comment by QarsoonMeel** [comment]
Right, I'm gonna sit down and rename some of those defs and fix up xml

**Comment by statecouncil** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/60186996/134001453-69ebcb6b-b720-4880-9f41-45c65eff88ed.png)
> > > > > I would to conflicting - Healthy instead
> > > > 
> > > > 
> > > > Hmm, how does that differ, technically?
> > > 
> > > 
> > > So one is: give this dream to pawns who are injured
> > > There other is: don't give this dream to pawns who are healthy
> > 
> > 
> > Right. But what difference does that make, in the end? No sarcasm, I'm really not sure.
> 
> We are checking if it has any injuries only (wounded). We but we wanna check if he is ill, injuried or in pain (not healthy).

aaaah, okay. Understood.

**Comment by statecouncil** [comment]
> Right, I'm gonna sit down and rename some of those defs and fix up xml

You want to rename them back to the original names? Also thank you. I'm learning a lot here.

**Comment by QarsoonMeel** [comment]
No worries man. I will rename them to original unless original did not follow the convention. 

In programming it is important what you are checking. If you wanna check just for wounds then yeah check wounded but if you wanna check if pawn is in any painful state then just say Pawn cannot be healthy :P

**Comment by statecouncil** [comment]
> ![image](https://user-images.githubusercontent.com/60186996/134001321-f2c4d678-6d0f-4397-8518-bf8a70babe12.png)
> Tribal exclusive? :P

Yeah, I thought about that, too. Let's do that.

**Comment by statecouncil** [comment]
> No worries man. I will rename them to original unless original did not follow the convention.
> 
> In programming it is important what you are checking. If you wanna check just for wounds then yeah check wounded but if you wanna check if pawn is in any painful state then just say Pawn cannot be healthy :P

Got it. Also, I've updated the Dream Inventory with these changes, if you need to refer to that.
