### ISSUE TITLE
[FEATURE] - Other races compatibility

### ISSUE THREAD

**Issue by statecouncil** [QarsoonMeel/DreamersDreams#37]
Managed to patch ALL races except the ones that are reinventing themselves (androids for example).

**Comment by statecouncil** [comment]
Not entirely serious, but we should eventually have a discussion about other species (and robot) compatibility.

**Comment by QarsoonMeel** [comment]
I will be investigating that tomorrow.

**Comment by statecouncil** [comment]
See https://github.com/QarsoonMeel/DreamersDreams/issues/28
