### ISSUE TITLE
[DREAM] - Ancient Danger

### ISSUE THREAD

**Issue by statecouncil** [QarsoonMeel/DreamersDreams#47]
Various dreams that the pawn that discovered the map's Ancient Danger can have.

When a pawn approached an ancient danger's wall, the player gets a letter informing them about it. This could mark that pawn for a Special Dream next time he sleeps, hinting towards the nature of the Ancient Danger. For every type of threat in there we should have several dreams ready, so the player can't be 100% certain what to expect. Is that doable on the tech side?

**Comment by QarsoonMeel** [comment]
I really don't understand what you are asking here. You want to anticipate threats? Or you want to give special dreams to pawn that discovered ancient danger?

**Comment by statecouncil** [comment]
Sorry, I'll try again.
The ancient danger buildings on the settlement's map are determined on map generation, including contents. It's a bit of a gamble opening them (as it should be), and having bad luck can easily lead to the destruction of the colony. I think giving the pawn that discovered it a dream regarding this situation might be an interesting gameplay addition. Note that some maps have more than one Ancient Danger, with varying content, so this by itself might make the dreams unreliable. Which might also not be a bad thing.

**Comment by QarsoonMeel** [comment]
I really can't think about an easy way to implement this. It will be tricky and the gameplay benefits will be very small imo.

**Comment by statecouncil** [comment]
Fair enough. Let's shelf it for now, to be revisited eventually.
