### ISSUE TITLE
[FEATURE] - Traumatizing Dreams

### ISSUE THREAD

**Issue by QarsoonMeel** [QarsoonMeel/DreamersDreams#48]
**Describe the idea you have**

> Based on my most recent dream: Traumatizing Dreams.
> Litterally dreams so bad that they are remembered for a long time and can cause a pawn to have a major mental breakdown, or manipulate it's social relationships depending on who they saw in the dream. Can cause a minor mental breakdown on waking up. Can only be dreamt by one person at a time, min. once a month, and max. once two years because your colony will become wasted if it happens that all of your pawns go insane from those dreams.

This idea was suggested by fan. Literally, this users name is fan.

**To Do**
- [ ] Discuss it. I really like the idea of long term dreams
- [ ] Minor breakdowns upon waking up from the dream?

**Comment by statecouncil** [comment]
Hmm, this kind of goes in a direction I had the other day. What if a dream like that, in game mechanics, was treated like an illness? A pawn gets it, and it keeps affecting im until it is "cured", strengthening in intensity the entire time. We should think about how to give the player some angle to control thought. If the whole system is completely uninteractive ("Oh god, my colony has a superbaddream _again_, and there's nothing I can do about it"), it won't be fun.
I do like the idea of some kind of really menacing threat in the dreamworld, waiting to strike.

**Comment by QarsoonMeel** [comment]
That's the problem. There is no way for us to interact with the system let's lets keep this idea closed until we will be ready to do it.
